networks:
  app-network:
    driver: bridge

services:

  # ASP.NET Core Web API Application
  shop-webapi:
    image: ${DOCKER_REGISTRY-}shop-webapi
    container_name: shop-webapi
    restart: always
    build:
      context: .
      dockerfile: src/Shop.PublicApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    expose:
      - 80
    ports:
      - "80:80"
    links:
      - shop-sql-server
      - shop-mongo-server
      - shop-redis
    networks:
      - app-network
    depends_on:
      - shop-sql-server
      - shop-mongo-server
      - shop-redis
      - shop-eventstore.db

  # SQL Server
  shop-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: shop-sql-server
    restart: always
    expose:
      - 1433
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pMA63033n6tF
    networks:
      - app-network

  # MongoDB Server
  shop-mongo-server:
    image: mongo:latest
    container_name: shop-mongo-server
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Redis Cache Server
  shop-redis:
    image: redis:latest
    container_name: shop-redis
    command: redis-server --requirepass pMA63033n6tF
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - app-network
  
  shop-eventstore.db:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    container_name: shop-eventstore.db
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
#    volumes:
#      - type: volume
#        source: eventstore-volume-data
#        target: /var/lib/eventstore
#      - type: volume
#        source: eventstore-volume-logs
#        target: /var/log/eventstore
    networks:
      - app-network